server:
  port: 0

spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/commerce_shopping_store_db"
    username: "postgres"
    password: "postgres"
  sql:
    init:
      mode: always